import logging
from dataclasses import dataclass

from dotenv import load_dotenv

from ai.prompts import build_guide_prompt, build_team_report_prompt
from ai.providers import AIRateLimitedError, AIUnavailableError, get_provider

load_dotenv()

logger = logging.getLogger(__name__)

# Re-exported for callers that catch it from here.
__all__ = ["AIUnavailableError", "GuideResult", "generate_efficiency_guide", "generate_team_report"]


@dataclass
class GuideResult:
    """A guide plus where it came from, so callers can tell real answers from fallbacks.

    source: "ai" (generated by the model), "rate_limited" or "unavailable" (static fallback).
    """
    tasks: list
    source: str

    @property
    def is_fallback(self):
        return self.source != "ai"


def generate_efficiency_guide(engineer_data, severity="moderate"):
    """
    Generates a personalized guide. Tone and length adjust based on severity.
    Never raises: on failure it returns a static fallback with source != "ai".
    """
    prompt = build_guide_prompt(engineer_data, severity)

    try:
        response_text = get_provider().generate(prompt).text

        tasks = []
        for line in response_text.split('\n'):
            line = line.strip()
            if line and line[0].isdigit() and '. ' in line[:4]:
                clean_text = line.split('. ', 1)[1].strip()

                # Strip out stray markdown asterisks that the AI ignores rules to include
                clean_text = clean_text.replace('**', '').replace('*', '')

                tasks.append({
                    "title": "Optimization Action",
                    "desc": clean_text
                })

        if not tasks:
            tasks = [{"title": "AI Summary", "desc": response_text.replace('**', '')}]

        return GuideResult(tasks=tasks, source="ai")

    except AIRateLimitedError:
        logger.warning("Gemini rate limit hit; serving the fallback runbook")
        return GuideResult(source="rate_limited", tasks=[
            {"title": "System Notice: API Rate Limit", "desc": "Personalized generation is paused due to Gemini API limits. Showing standard procedures."},
            {"title": "Audit Token Looping", "desc": "Check agent logs for repetitive, failing task loops."},
            {"title": "Enforce Model Tiering", "desc": "Shift non-essential background tasks to Haiku/Flash models."},
            {"title": "Consolidate Prompts", "desc": "Batch multiple instructions into a single context window."}
        ])
    except Exception as e:
        # Total API failure (no internet, no API key, server error)
        logger.error("Gemini guide generation failed (%s): %s", type(e).__name__, e)
        return GuideResult(source="unavailable", tasks=[
            {"title": "AI Service Offline", "desc": "Unable to connect to the intelligence engine."},
            {"title": "Manual Intervention", "desc": "Please review the raw telemetry metrics directly."}
        ])


def generate_team_report(team_summary):
    prompt = build_team_report_prompt(team_summary)

    try:
        return get_provider().generate(prompt).text.replace('**', '')
    except Exception as e:
        logger.error("Gemini team report failed (%s): %s", type(e).__name__, e)
        return "Error generating team report: System Offline."
